### ISSUE TITLE
Errors trying to npm install and npm start

### ISSUE THREAD

**Issue by lucifudge** [Revadike/epicgames-freebies-claimer#95] opened 2021-05-31 04:38 UTC
> I generated "device_auths.json" and placed it in the same directory as the project
> Installed nodejs (node-v16.2.0-x64.msi)
> Opened "node.js command prompt"
> Changed working directory to path of 1.5.0 source
> ran "npm install"
> ran "npm start", returned **npm ERR! Missing script: "start"**
> repaired nodejs install
> reran "npm install"
> different error this time;
```
npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno -4058
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\SFF\AppData\Local\npm-cache\_logs\2021-05-31T04_30_37_093Z-debug.log
```
[2021-05-31T04_30_37_093Z-debug.log](https://github.com/Revadike/epicgames-freebies-claimer/files/6567774/2021-05-31T04_30_37_093Z-debug.log)

**Comment by Revadike** [comment] 2021-05-31 08:53
Try installing https://git-scm.com/downloads

**Comment by Revadike** [comment] 2021-05-31 15:11
Dupe of https://github.com/Revadike/epicgames-freebies-claimer/issues/44

**Closed by Revadike** 2021-05-31 15:11 UTC
