### ISSUE TITLE
Claimer is unable to claim any freebies & changes "Found" to 0 freebies.

### ISSUE THREAD

**Issue by Nicklordzero** [Revadike/epicgames-freebies-claimer#178] opened 2021-12-21 02:21 UTC
### Expected Behavior
The claimer should be claiming the free mystery games but boots up & sees 1 unclaimed freebies then says FOUND 0 freebies without claiming them. No email receipts or anything...

### Actual Behavior
[32m 2021-12-20 | 18:17:11.651 | INFO  | Epicgames Freebies Claimer (1.5.8) by Revadike[39m
[32m 2021-12-20 | 18:17:14.413 | INFO  | Found 0 unclaimed freebie(s) for REDACTEDINFO[39m
[32m 2021-12-20 | 18:17:15.436 | INFO  | Found 0 unclaimed freebie(s) for REDACTEDINFO[39m
[32m 2021-12-20 | 18:17:16.418 | INFO  | Found 0 unclaimed freebie(s) for REDACTEDINFO[39m

### Specifications

  - `epicgames-freebies-claimer` Version: master commit: 1f213db0f411732fa456009b1cf4777a13c716f4
  - Platform / OS: Microsoft Windows 10
  - Node Version: 21H2

**Comment by BinnyDevel** [comment] 2021-12-21 02:41
read #172

**Comment by Nicklordzero** [comment] 2021-12-21 03:23
> read #172

Doesn't help. Need a solution!

**Comment by BinnyDevel** [comment] 2021-12-21 06:47
it won't be solved until captcha is figured out bro

**Comment by Revadike** [comment] 2022-01-01 15:34
Dupe of  #172

**Closed by Revadike** 2022-01-01 15:34 UTC
Labels: bug
