### ISSUE TITLE
Error Code 1 and unsupported Engine

### ISSUE THREAD

**Issue by ni920** [Revadike/epicgames-freebies-claimer#85] opened 2021-01-15 13:04 UTC
Does somebody know what that means ? 

![Bildschirmfoto 2021-01-15 um 14 00 49](https://user-images.githubusercontent.com/40561468/104730325-22e3b480-573a-11eb-8de2-500c32968d6d.png)

![Bildschirmfoto 2021-01-15 um 14 03 14](https://user-images.githubusercontent.com/40561468/104730479-6c340400-573a-11eb-8069-15251acfc064.png)

**Comment by Revadike** [comment] 2021-01-15 13:38
Dupe of https://github.com/Revadike/epicgames-freebies-claimer/issues/58

**Closed by Revadike** 2021-01-15 13:38 UTC
