### ISSUE TITLE
Git submodule error

### ISSUE THREAD

**Issue by NaolShow** [Revadike/epicgames-freebies-claimer#40] opened 2020-07-02 18:35 UTC
Hi everyone, I tried to install this script on my raspberry pi and it didn't worked, so I tried on my windows and it also didn't worked, I have npm, nodejs and also git. I updated all of them even the OS but I still have this error:
```
>npm install
npm ERR! code 128
npm ERR! Command failed: git submodule update -q --init --recursive
npm ERR! fatal: No url found for submodule path 'docs/.vuepress/dist' in .gitmodules
npm ERR!
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\MyUser\AppData\Roaming\npm-cache\_logs\2020-07-02T18_30_39_464Z-debug.log
```
When I use the sudo keyword on my raspberry pi, I have:
```
npm ERR! code 128
npm ERR! Command failed: git clone --depth=1 -q -b develop git://github.com/Revadike/node-epicgames-client.git /root/.npm/_cacache/tmp/git-clone-a37cbbd3
npm ERR! fatal: could not create leading directories of '/root/.npm/_cacache/tmp/git-clone-a37cbbd3': Permission denied
npm ERR!

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-07-02T18_36_56_092Z-debug.log
```

Here's the complete log: https://pastebin.com/pPe3bACm

Thanks for your help

**Comment by lgjx123** [comment] 2020-07-03 03:30
same error for me

**Comment by wangwei8828** [comment] 2020-07-03 05:54
same

**Comment by DeusDE** [comment] 2020-07-03 10:32
the new version also doesnt work for me, but 1.4.0 works perfectly

**Comment by zanmat0** [comment] 2020-07-08 15:17
Same here

**Comment by gab** [comment] 2020-07-09 19:33
The error is with https://github.com/Revadike/node-epicgames-client which is listed as a dependency. If you checkout that repo on its own you can reproduce the same error. The issue is that the docs/.vuepress/dist file has been checked in as a gitlink (id 16000), without a corresponding defined submodule in a .gitmodules file.

I don't know whether this is supposed to be an actual submodule, but `git rm` on this file does allows the `git submodule` command to pass without triggering an error. Not sure if it'd fail further into the process.

```
d:\node-epicgames-client (master) (epicgames-client@2.0.22)
λ git submodule update -q --init --recursive
fatal: No url found for submodule path 'docs/.vuepress/dist' in .gitmodules

d:\node-epicgames-client (master) (epicgames-client@2.0.22)
λ git ls-tree HEAD docs/.vuepress/dist
160000 commit dcf112ed81d20e64b97e9a09379b95beefe64c95  docs/.vuepress/dist

d:\node-epicgames-client (master) (epicgames-client@2.0.22)
λ git rm docs\.vuepress\dist\
rm 'docs/.vuepress/dist'

d:\node-epicgames-client (master) (epicgames-client@2.0.22)
λ git submodule update -q --init --recursive

d:\node-epicgames-client (master) (epicgames-client@2.0.22)
λ
```

**Comment by gab** [comment] 2020-07-09 19:52
Actually the issue with node-epicgames-client is from upstream, I've filed an issue: https://github.com/SzymonLisowiec/node-epicgames-client/issues/100

**Comment by louga31** [comment] 2020-07-16 09:27
Fixed the issue in my fork:
Replace your package.json by this (It just changes the epicgames-client source to my fork and change the version number):
```json
{
    "name": "epicgames-freebies-claimer",
    "version": "2.0.25",
    "description": "Claim free game promotions from the Epic Game Store",
    "author": "Revadike <https://revadike.com>",
    "main": "claimer.js",
    "scripts": {
        "test": "echo \"Error: no test specified\" && exit 1",
        "start": "node claimer.js"
    },
    "license": "MIT",
    "repository": {
        "type": "git",
        "url": "git+https://github.com/revadike/epicgames-freebies-claimer.git"
    },
    "bugs": {
        "url": "https://github.com/revadike/epicgames-freebies-claimer/issues"
    },
    "homepage": "https://github.com/revadike/epicgames-freebies-claimer",
    "url": "https://github.com/revadike/epicgames-freebies-claimer",
    "devDependencies": {
        "eslint": "^6.8.0"
    },
    "dependencies": {
        "check-update-github": "0.0.4",
        "colors": "^1.4.0",
        "epicgames-client": "github:louga31/node-epicgames-client#master",
        "epicgames-client-login-adapter": "^0.1.2",
        "node-2fa": "^1.1.2",
        "tracer": "^1.1.2"
    }
}
```
I also fixed the client.freeGamesPromotions is not a function issue in this fork

**Comment by Revadike** [comment] 2020-07-16 10:52
> Actually the issue with node-epicgames-client is from upstream, I've filed an issue: [SzymonLisowiec/node-epicgames-client#100](https://github.com/SzymonLisowiec/node-epicgames-client/issues/100)

Thanks for finding this out. I'm sorry for not looking into this earlier. It seems @SzymonLisowiec is no longer able to actively maintain his library, hence I made my fork. I've implemented your solution into my fork and this resolves this issue.

**Closed by Revadike** 2020-07-16 10:52 UTC
