### ISSUE TITLE
Cant claim the new Free "daily" giveaway

### ISSUE THREAD

**Issue by Bobu5** [Revadike/epicgames-freebies-claimer#169] opened 2021-12-17 01:08 UTC
### Expected Behavior
it would claim the free daily games

### Actual Behavior
it would spit out `Error: Unable to acquire purchase token` instead (see the error in screenshot below)
![image](https://user-images.githubusercontent.com/87025837/146471720-a95e7ad1-72e9-42c5-a2b8-b95a88d0ea22.png)

### Steps to Reproduce the Problem

  1.  npm start in the root directory of the efc
  2.  get meowed by it , seems like it use another format than the weekly giveaway

### Specifications

  - `epicgames-freebies-claimer` Version: Latest (1.5.7)
  - Platform / OS:  Windows 10 21H2
 
![image](https://user-images.githubusercontent.com/87025837/146471890-62e85bb7-8d58-453f-8c03-8579229cf916.png)

  - Node Version:  '16.13.1'
  
![image](https://user-images.githubusercontent.com/87025837/146471838-b726d7eb-55a6-4295-bd29-fafd459f688f.png)

**Comment by Revadike** [comment] 2021-12-17 01:41
Dupe of https://github.com/Revadike/epicgames-freebies-claimer/issues/166#issuecomment-996185386

**Closed by Revadike** 2021-12-17 01:41 UTC
Labels: bug
