### ISSUE TITLE
Invalid login selector 

### ISSUE THREAD

**Issue by LionZXY** [Revadike/epicgames-freebies-claimer#75] opened 2020-12-26 20:13 UTC
Please, update your fork:

https://github.com/Revadike/node-epicgames-client-login-adapter

Now we get a error:
```
TimeoutError: waiting for selector "#login:not(:disabled)" failed: timeout 30000ms exceeded
    at new WaitTask (/Users/nikitakulikov/private/epicgames-freebies-claimer/node_modules/puppeteer/lib/DOMWorld.js:549:28)
    at DOMWorld._waitForSelectorOrXPath (/Users/nikitakulikov/private/epicgames-freebies-claimer/node_modules/puppeteer/lib/DOMWorld.js:478:22)
    at DOMWorld.waitForSelector (/Users/nikitakulikov/private/epicgames-freebies-claimer/node_modules/puppeteer/lib/DOMWorld.js:432:17)
    at Frame.waitForSelector (/Users/nikitakulikov/private/epicgames-freebies-claimer/node_modules/puppeteer/lib/FrameManager.js:627:47)
    at Frame.<anonymous> (/Users/nikitakulikov/private/epicgames-freebies-claimer/node_modules/puppeteer/lib/helper.js:112:23)
    at Page.waitForSelector (/Users/nikitakulikov/private/epicgames-freebies-claimer/node_modules/puppeteer/lib/Page.js:1122:29)
    at Function.authenticate (/Users/nikitakulikov/private/epicgames-freebies-claimer/node_modules/epicgames-client-login-adapter/index.js:119:38)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
    at async Function.init (/Users/nikitakulikov/private/epicgames-freebies-claimer/node_modules/epicgames-client-login-adapter/index.js:204:7)
    at async /Users/nikitakulikov/private/epicgames-freebies-claimer/claimer.js:110:28
```

**Comment by Revadike** [comment] 2020-12-26 21:24
Feel free to send a PR

**Comment by LionZXY** [comment] 2020-12-27 00:03
@Revadike https://github.com/Revadike/node-epicgames-client-login-adapter/pull/3

**Comment by Revadike** [comment] 2021-05-31 15:00
Dupe of https://github.com/Revadike/epicgames-freebies-claimer/issues/66

**Closed by Revadike** 2021-05-31 15:00 UTC
