### ISSUE TITLE
ERROR | Failed to claim Cities

### ISSUE THREAD

**Issue by TT-IPIP** [Revadike/epicgames-freebies-claimer#194] opened 2022-03-15 07:35 UTC
```
ERROR | Failed to claim Cities: Skylines (Error: We could not confirm your purchase at this time.  Please try again later.)

**Comment by Revadike** [comment] 2022-03-15 12:52
Dupe of https://github.com/Revadike/epicgames-freebies-claimer/issues/172

**Closed by Revadike** 2022-03-15 12:52 UTC
Labels: bug
