### ISSUE TITLE
Game was already claimed

### ISSUE THREAD

**Issue by AdriDevelopsThings** [Revadike/epicgames-freebies-claimer#174] opened 2021-12-19 17:45 UTC
### Expected Behavior

The new free game "The Vanishing of Ethan Carter" should be claimed by epicgames-feebies-claimer.

### Actual Behavior

epicgames-feebies-claimer logged this and didn't claim the game:
```
 2021-12-19 | 18:40:39.668 | INFO  | Epicgames Freebies Claimer (1.5.8) by Revadike
 2021-12-19 | 18:40:44.721 | INFO  | Found 1 unclaimed freebie(s) for myemgail@gmail.com
 2021-12-19 | 18:40:49.497 | INFO  | Logged in as myaccount (myuuid)
 2021-12-19 | 18:40:54.539 | WARN  | The Vanishing of Ethan Carter was already claimed for this account
 2021-12-19 | 18:40:55.049 | INFO  | Logged myaccount out of Epic Games
```

The game is a 18+ game: Maybe the problem is the age restriction.

### Steps to Reproduce the Problem

start the script with ``npm start`` and try to claim the game.

### Specifications

  - `epicgames-freebies-claimer` Version: current main branch
  - Platform / OS:  Windows 11 (current version)
  - Node Version: v16.8.0

**Comment by Revadike** [comment] 2021-12-19 17:56
Dupe of https://github.com/Revadike/epicgames-freebies-claimer/issues/172

**Closed by Revadike** 2021-12-19 17:56 UTC
Labels: bug
