### ISSUE TITLE
Doesn't work, Epic games has now bot protections 

### ISSUE THREAD

**Issue by UNITY002** [Revadike/epicgames-freebies-claimer#125] opened 2021-09-10 04:17 UTC
Doesn't work. Epic games are using Recaptcha now

**Comment by Revadike** [comment] 2021-09-10 12:07
They've been using recaptcha for months. They don't always show it, it depends on the status of your account/IP. 

Dupe of https://github.com/Revadike/epicgames-freebies-claimer/issues/61

**Closed by Revadike** 2021-09-10 12:07 UTC
Labels: bug
