### ISSUE TITLE
Can we fix or resolve the CAPTCHA manually in game claim function (not the login captcha) ?

### ISSUE THREAD

**Issue by YogaSakti** [Revadike/epicgames-freebies-claimer#70] opened 2020-12-19 18:34 UTC
![image](https://user-images.githubusercontent.com/24309806/102696755-30a13980-4263-11eb-8f35-1c63efb64615.png)

**Comment by Revadike** [comment] 2021-05-31 14:56
Dupe of https://github.com/Revadike/epicgames-freebies-claimer/issues/61

**Closed by Revadike** 2021-05-31 14:56 UTC
