### ISSUE TITLE
That happens but idk how to fix it

### ISSUE THREAD

**Issue by theoware** [Revadike/epicgames-freebies-claimer#58] opened 2020-09-20 17:13 UTC
This happens:
```
C:\Users\user\Downloads\epicgames-freebies-claimer-master>npm start

> epicgames-freebies-claimer@1.4.1 start C:\Users\user\Downloads\epicgames-freebies-claimer-master
> node claimer.js

 2020-09-20 | 19:10:19.587 | ERROR | Error: ENOENT: no such file or directory, mkdir 'C:\Users\user\Downloads\epicgames-freebies-claimer-master\.egstore\a0ef9b22b34d3f3e6ab88ad0bad3d89ce208f5fab8909742596878999699d0eb'
    at Object.mkdirSync (fs.js:921:3)
    at new Launcher (C:\Users\user\Downloads\epicgames-freebies-claimer-master\node_modules\epicgames-client\src\Client\index.js:109:10)
    at C:\Users\user\Downloads\epicgames-freebies-claimer-master\claimer.js:79:26
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  errno: -4058,
  syscall: 'mkdir',
  code: 'ENOENT',
  path: 'C:\\Users\\user\\Downloads\\epicgames-freebies-claimer-master\\.egstore\\a0ef9b22b34d3f3e6ab88ad0bad3d89ce208f5fab8909742596878999699d0eb'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! epicgames-freebies-claimer@1.4.1 start: `node claimer.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the epicgames-freebies-claimer@1.4.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\user\AppData\Roaming\npm-cache\_logs\2020-09-20T17_10_19_618Z-debug.log
```
The log: https://pastebin.com/AVek7bVS

**Comment by Qdelta** [comment] 2020-09-21 05:37
Create a folder named .egstore and try again
This problem was noted already:
https://github.com/Revadike/epicgames-freebies-claimer/issues/53

**Comment by theoware** [comment] 2020-09-21 15:59
Now I get the following output: 
`C:\Users\user\Downloads\epicgames-freebies-claimer-master>npm start "*Email*" "*Password*"

> epicgames-freebies-claimer@1.4.1 start C:\Users\user\Downloads\epicgames-freebies-claimer-master
> node claimer.js "*Email*" "*Password*"

 2020-09-21 | 17:56:50.552 | WARN  | Invalid captcha!
 2020-09-21 | 17:56:50.552 | WARN  | Failed to login as *Email*, please attempt manually.
 2020-09-21 | 17:57:27.306 | ERROR | TimeoutError: waiting for selector "#login-with-epic" failed: timeout 30000ms exceeded
    at new WaitTask (C:\Users\user\Downloads\epicgames-freebies-claimer-master\node_modules\puppeteer\lib\DOMWorld.js:549:28)
    at DOMWorld._waitForSelectorOrXPath (C:\Users\user\Downloads\epicgames-freebies-claimer-master\node_modules\puppeteer\lib\DOMWorld.js:478:22)
    at DOMWorld.waitForSelector (C:\Users\user\Downloads\epicgames-freebies-claimer-master\node_modules\puppeteer\lib\DOMWorld.js:432:17)
    at Frame.waitForSelector (C:\Users\user\Downloads\epicgames-freebies-claimer-master\node_modules\puppeteer\lib\FrameManager.js:627:47)
    at Frame.<anonymous> (C:\Users\user\Downloads\epicgames-freebies-claimer-master\node_modules\puppeteer\lib\helper.js:112:23)
    at Page.waitForSelector (C:\Users\user\Downloads\epicgames-freebies-claimer-master\node_modules\puppeteer\lib\Page.js:1122:29)
    at Function.authenticate (C:\Users\user\Downloads\epicgames-freebies-claimer-master\node_modules\epicgames-client-login-adapter\index.js:113:46)
    at Function.init (C:\Users\user\Downloads\epicgames-freebies-claimer-master\node_modules\epicgames-client-login-adapter\index.js:204:18)
    at async C:\Users\user\Downloads\epicgames-freebies-claimer-master\claimer.js:110:28
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! epicgames-freebies-claimer@1.4.1 start: `node claimer.js "*Email*" "*Password*"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the epicgames-freebies-claimer@1.4.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\user\AppData\Roaming\npm-cache\_logs\2020-09-21T15_57_27_420Z-debug.log`

**Comment by Qdelta** [comment] 2020-09-21 16:20
Hey Mate, try to open chrome yourself and login to epic games.
Then try to run the script again.

(it seems to want to use the cookie from chrome and if you login yourself via chrome, it seems to not give the captcha problem)
btw: I only started using this script like 2 days ago, so sorry for my limited answers / explanation

**Comment by theoware** [comment] 2020-09-23 12:47
Still not working

**Comment by GhustOne** [comment] 2020-09-24 23:06
Having same problem, It worked but stopped working after I updated Node.js. Tried deleting the whole folder and starting again and uninstalling Node.js and reinstalling multiple times (tried different versions and same version) the version that worked was 12.18.4, Going to 14.12.0 made it stop working.

**Comment by sakuyamaij** [comment] 2020-10-04 11:30
> Create a folder named .egstore and try again
> This problem was noted already:
> #53

Work on my Raspberry Pi. Thanks!

**Comment by Revadike** [comment] 2021-05-31 14:48
Dupe of https://github.com/Revadike/epicgames-freebies-claimer/issues/43

**Closed by Revadike** 2021-05-31 14:48 UTC
