### ISSUE TITLE
What does this error mean?

### ISSUE THREAD

**Issue by xiang32** [Revadike/epicgames-freebies-claimer#191] opened 2022-02-11 04:29 UTC
Once I use this claimer, I got an error like this:

![tmp2](https://user-images.githubusercontent.com/27066986/153537702-3d4036c5-c6fc-403b-918c-3c38f503e8bd.jpg)

What should I do?

**Comment by xiang32** [comment] 2022-02-12 09:00
> You have to face the hCaptcha challenge.

Thank you. Could you tell me what should I do to solve the hCaptcha?

**Comment by RatedR9** [comment] 2022-02-13 09:34
隔这中文聊天

**Comment by Revadike** [comment] 2022-02-14 20:48
Dupe of https://github.com/Revadike/epicgames-freebies-claimer/issues/172

> 蚌珠了，推荐使用 [Epic免费人](https://github.com/QIN2DIM/epic-awesome-gamer) ~

@QIN2DIM Please refrain from advertising your own project here. Instead, consider contributing to this project. Thank you.

**Closed by Revadike** 2022-02-14 20:48 UTC
Labels: question
