### ISSUE TITLE
Error: Unknown quick purchase status: false

### ISSUE THREAD

**Issue by ProximalPod** [Revadike/epicgames-freebies-claimer#22] opened 2020-05-14 21:42 UTC
6:42:07 PM web.1 |       body:
6:42:07 PM web.1 |        { errorCode:
6:42:07 PM web.1 |           'errors.com.epicgames.ecommerce.orderprocessor.invalid_offer_from_catalog_service',
6:42:07 PM web.1 |          errorMessage:
6:42:07 PM web.1 |           'Sorry, the effective date 2099-01-01T00:00:00.000Z is in the future, purchase of offer 3e3aedb497074b6e878343bac1011d60 is rejected for epic account ebcc6f88cb314aa7914069e0bb81e542.',
6:42:07 PM web.1 |          messageVars: [Array],
6:42:07 PM web.1 |          numericErrorCode: 2007,
6:42:07 PM web.1 |          originatingService: 'com.epicgames.orderprocessor.public',
6:42:07 PM web.1 |          intent: 'prod' } } }

**Comment by Revadike** [comment] 2020-05-14 22:00
Yeah, the problem is that it's trying to purchase the wrong offer. I don't know why the query I'm using returns the wrong offer. I'm currently investigating this.

[Correct offer](https://launcher-website-prod07.ol.epicgames.com/purchase?showNavigation=true&namespace=0584d2013f0149a791e7b9bad0eec102&offers=954871df36d3456ca1face43aa5c2e62#/purchase/verify?_k=x1wf7o) vs [wrong offer](https://launcher-website-prod07.ol.epicgames.com/purchase?showNavigation=true&namespace=d5241c76f178492ea1540fce45616757&offers=3e3aedb497074b6e878343bac1011d60#/purchase/verify?_k=x1wf7o)

**Comment by ProximalPod** [comment] 2020-05-14 22:03
Maybe it's related to the site being completely fucked up most of today?

**Comment by Revadike** [comment] 2020-05-14 22:05
> Maybe it's related to the site being completely fucked up most of today?

Well, it certainly limits my debugging.

**Comment by ProximalPod** [comment] 2020-05-14 22:08
Maybe I can help. Can you point me to where the JQL query syntax is documented, if anywhere?

**Comment by fer662** [comment] 2020-05-14 22:10
Maybe I can help. Can you point me to where the JQL query syntax is documented, if anywhere? (oops wrong account)

**Comment by Revadike** [comment] 2020-05-14 22:12
I'm using the query in `graphql.js`. There is no documentation. It's reverse engineered.

**Comment by Revadike** [comment] 2020-05-14 22:23
Okay, so this is what they seem to have changed:
![image](https://user-images.githubusercontent.com/4411977/81991740-3b974a00-9642-11ea-9101-32b22765fda8.png)

The first mystery game is GTA V, but it's not the right offer.

**Comment by ProximalPod** [comment] 2020-05-14 22:24
@Revadike yeah I just logged before the filtering and arrived to mostly the same conclusion. Weird that the api is out of sync with the site though. I wonder if we can filter by price without filtering by the category and find it like that.

**Comment by Revadike** [comment] 2020-05-14 22:25
> @Revadike yeah I just logged before the filtering and arrived to mostly the same conclusion. Weird that the api is out of sync with the site though. I wonder if we can filter by price without filtering by the category and find it like that.

As you can see, it's not out of sync. The free games category is just still outdated.

**Comment by Revadike** [comment] 2020-05-14 23:04
I found this new endpoint, which could replace the current query. However, it still returns outdated offer, just like the query: https://store-site-backend-static.ak.epicgames.com/freeGamesPromotions?locale=en-US&country=NL&allowCountries=NL

**Comment by chaoscreater** [comment] 2020-05-22 08:00
How's the troubleshooting on this one? New game up today (Civilization VI) and still getting the same error message when using the script. Really miss not having to claim games manually!

**Comment by Revadike** [comment] 2020-05-22 10:36
> How's the troubleshooting on this one? New game up today (Civilization VI) and still getting the same error message when using the script. Really miss not having to claim games manually!

Do you have the latest version? It worked fine for me this time around.

**Comment by lingsamuel** [comment] 2020-05-22 14:37
Still have this problem.

**Comment by Gonzira** [comment] 2020-05-22 14:45
I have the same problem. It fails to claim the game. Even when I've already claimed it manually though Epic game launcher, I tried to run the script again, strangely it gives me the same error even though I already have the game on my account. 

Here is a complete text of error : `2020-05-22 | 17:26:47.083 | ERROR | Error: Unknown quick purchase status: false
    at Launcher.purchase (f:\Program Files (x86)\epicgames-freebies-claimer\node_modules\epicgames-client\src\Client\index.js:645:15)
    at process._tickCallback (internal/process/next_tick.js:68:7)`

Also I've tracked the error where it originates and found a POST method called "quickPurchase" which is located in Index.js (node_modules\epicgames-client\src\Client)
it shows me this `message:"errors.com.epicgames.ecommerce.orderprocessor.invalid_offer_from_catalog_service" `

**Comment by lingsamuel** [comment] 2020-05-22 20:41
I am quiet sure Epic use a placeholder namespace to implement the "Mystery Games" while the query `searchStoreQuery` returns games with same namespaces `d5241c76f178492ea1540fce45616757`.

In the [free-games](https://www.epicgames.com/store/en-US/free-games) page, I believe they use [freeGamesPromotions](https://store-site-backend-static.ak.epicgames.com/freeGamesPromotions?locale=en-US&country=NL&allowCountries=NL) to get the `productSlug` or `urlSlug` to build the real url (while the `free-games` page button is a link) without access SKU's real namespace and id. Evidence is the Civ's image is a `href` link of it's product page `https://www.epicgames.com/store/en-US/product/sid-meiers-civilization-vi`.


But the strange thing is in the product detail page, their first graphql  has the `namespace` variable:
![image](https://user-images.githubusercontent.com/14567045/82707083-eac0ca80-9cad-11ea-9542-bf97d5e356fa.png)

While these requests are sent at the same time, I found that the script knows everything they (and we) need:
![image](https://user-images.githubusercontent.com/14567045/82707767-48094b80-9caf-11ea-985b-0fda9b26f25e.png)

I don't know how they get it, didn't find anything suspect. The script and html doesn't contains ns and id in plaintext, maybe they are encoded to another format?

**Comment by chaoscreater** [comment] 2020-05-23 10:42
> 
> 
> > How's the troubleshooting on this one? New game up today (Civilization VI) and still getting the same error message when using the script. Really miss not having to claim games manually!
> 
> Do you have the latest version? It worked fine for me this time around.

I definitely have the latest version.

**Comment by Revadike** [comment] 2020-05-23 12:55
sorry guys, my fault. I forgot to update my github repo, because i was waiting for `node-epicgames-client` to update with my PR's. 
Next update it should be fixed!

**Comment by ProximalPod** [comment] 2020-05-26 16:20
@Revadike you should just point the dependency to your fork of node-epicgames-client, they still haven't merged. Is it just that that's needed, or there are some changes in this repo as well?

**Comment by Revadike** [comment] 2020-05-26 17:07
> @Revadike you should just point the dependency to your fork of node-epicgames-client, they still haven't merged. Is it just that that's needed, or there are some changes in this repo as well?

they need to be merged before I can update this. I'm waiting on that.

**Comment by MrCalv1n** [comment] 2020-06-01 20:05
Hi @Revadike!

Any news about this subject?

**Comment by fer662** [comment] 2020-06-01 21:13
They don't need to merge, you can make npm point to a fork of node-epicgames-client which has your pull request in it.

**Comment by Revadike** [comment] 2020-06-01 23:02
PR's were merged, but other issues arose unfortunately. I'm working on it.

**Comment by Revadike** [comment] 2020-06-04 18:12
Everyone has this issue right now. I need help investigating the purchase flow of node-epicgames-client.

**Comment by chaoscreater** [comment] 2020-06-17 06:56
It has been almost 2 weeks. Any luck so far? Really love your project and would be nice to make it work again.

**Comment by Revadike** [comment] 2020-06-17 14:34
![image](https://user-images.githubusercontent.com/4411977/84911341-4f5a2400-b0b8-11ea-860e-bf6e5c304920.png)
![image](https://user-images.githubusercontent.com/4411977/84911372-584af580-b0b8-11ea-8344-b294a2f34743.png)

**Comment by Revadike** [comment] 2020-07-16 11:01
Quick update: I'm currently rewriting the project to work with puppeteer instead. It will sadly be more resource intensive, but it will allow us to bypass the purchase flow API and be more flexible in general.

**Comment by Revadike** [comment] 2021-05-31 14:28
> Quick update: I'm currently rewriting the project to work with [puppeteer](https://github.com/Revadike/epicgames-freebies-claimer/tree/puppeteer) instead. It will sadly be more resource intensive, but it will allow us to bypass the purchase flow API and be more flexible in general.

Uh, maybe another time, but for now I managed to fix the current repo. 
The quickpurchase method from `node-epicgames-client` has been disabled, so this error shouldn't happen anymore.

**Closed by Revadike** 2021-05-31 14:28 UTC
Labels: bug, help wanted
