### ISSUE TITLE
WARN | Failed to claim TITLE(Error: Unable to acquire purchase token)(CHANGE THIS!) A Descriptive Title

### ISSUE THREAD

**Issue by CriticalE** [Revadike/epicgames-freebies-claimer#171] opened 2021-12-17 16:46 UTC
Hello guys, well I wanna know if this still working, because no matter what I do failed to claim it, in explorer can be without problem but I will try use that because have many accounts, no matter if add 1, 2 or 3 accounts, it give same error as title always, I share information of platform and so for future fix please, thanks for all and hope this can be fixed to soon :(

### Specifications

  - `epicgames-freebies-claimer` Version: 1.5.7
  - Platform / OS: Windows 10
  - Node Version: 17.2.0

**Comment by mgn-norm** [comment] 2021-12-17 17:04
if you go to the website and claim it manually, it seems like they've added a CAPTCHA to the purchase. Not sure if there's a way to work around this.

**Comment by Revadike** [comment] 2021-12-17 17:11
Dupe of https://github.com/Revadike/epicgames-freebies-claimer/issues/166

**Closed** 2021-12-18 20:42 UTC
Labels: bug, duplicate
