### ISSUE TITLE
| WARN | Rise of the Tomb Raider: 20 Year Celebration was already claimed for this account

### ISSUE THREAD

**Issue by daeeros** [Revadike/epicgames-freebies-claimer#183] opened 2021-12-30 18:18 UTC
2021-12-30 | 21:16:41.874 | WARN  | Rise of the Tomb Raider: 20 Year Celebration was already claimed for this account
 2021-12-30 | 21:16:44.747 | WARN  | Tomb Raider GAME OF THE YEAR EDITION was already claimed for this account
 2021-12-30 | 21:16:47.822 | WARN  | Shadow of the Tomb Raider: Definitive Edition was already claimed for this account

I getting this warnings, but in my account not have this games, and this warnings says all games what i dont have

### Specifications

  - `epicgames-freebies-claimer` Version: 
  - Platform / OS:  Ubuntu 18.04 LTS
  - Node Version: v14.17.5

**Comment by Nicklordzero** [comment] 2021-12-30 20:40
Because the developer isn't being active with his own github. Theirs a massive error that hasn't been fixed by this dev. IDK what else to do either bud. Just redeem it yourself.

**Comment by adi170-alt** [comment] 2021-12-30 21:01
Dupe of #172

**Closed** 2021-12-31 22:06 UTC
Labels: bug
