### ISSUE TITLE
it starts but can't login

### ISSUE THREAD

**Issue by amazing355** [Revadike/epicgames-freebies-claimer#84] opened 2021-01-15 07:42 UTC
![123](https://user-images.githubusercontent.com/26679868/104695769-4b5db580-571e-11eb-9585-057e132a517b.png)

it doesn't login

**Comment by jerryyjz** [comment] 2021-02-04 08:40
the same here

**Comment by damianoooo** [comment] 2021-02-07 17:27
i have the same issue

**Comment by lorejoh12** [comment] 2021-03-05 22:16
There's a few of reports of this- the root cause seems to be that Epic changed the #id on the blue Login button in the log in flow. The bug isn't actually in this repo, it's in epicgames-client-login-adapter package.

Anyone who is hitting this and doesn't want to wait for an update, in the meantime after running `npm install` you can go to the file node_modules\epicgames-client-login-adapter\index.js and change line 120 to:
      `const loginButton = await page.waitForSelector('#sign-in:not(:disabled)');`
("sign-in" is the new id of the button). Note that you'll need to update this again if you ever have to force install npm dependencies.

and then it should work as normal.

There's already an open PR to fix it: https://github.com/Revadike/node-epicgames-client-login-adapter/pull/4, just letting others know since the solution isn't obvious as it's in a dependency file.

**Comment by Revadike** [comment] 2021-05-31 15:05
Dupe of https://github.com/Revadike/epicgames-freebies-claimer/issues/66

**Closed by Revadike** 2021-05-31 15:05 UTC
