### ISSUE TITLE
Failed to claim

### ISSUE THREAD

**Issue by Wunderharke** [Revadike/epicgames-freebies-claimer#24] opened 2020-05-15 11:38 UTC
Hi,

I'm struggling with following error: "Error: Unknown quick purchase status: false"
Is there any easy fix for this?
I appreciate any help :)

**Comment by Revadike** [comment] 2020-05-15 11:44
Dupe of https://github.com/Revadike/epicgames-freebies-claimer/issues/22

**Closed by Revadike** 2020-05-15 11:44 UTC
