### ISSUE TITLE
npm install ERROR

### ISSUE THREAD

**Issue by jiajiaxd** [Revadike/epicgames-freebies-claimer#59] opened 2020-09-21 15:16 UTC
When I use npm install,it says
![image](https://user-images.githubusercontent.com/51043917/93785135-5157f400-fc60-11ea-8c31-e782adf86c49.png)

Linux Debian
Arm64

**Comment by advaitmanav** [comment] 2020-10-01 16:52
![image](https://user-images.githubusercontent.com/72219487/94839286-6557de80-0434-11eb-9245-df57c338e349.png)

Got same error, how to fix this?
Windows 10 x64

**Comment by Revadike** [comment] 2020-10-01 17:12
I think you need to install Git

**Comment by jiajiaxd** [comment] 2020-10-02 01:31
I have installed Git

**Comment by FlickZexe** [comment] 2020-12-27 00:27
same

**Comment by FlickZexe** [comment] 2020-12-27 00:39
So um yeah, I had that, I actually installed git again, then followed this 

> Have you correctly set your PATH to point at your Git installation?

You need to add the following paths to PATH:

C:\Program Files\Git\bin\
C:\Program Files\Git\cmd\
And check that these paths are correct – you may have Git installed on a different drive, or under Program Files (x86). Correct the paths if necessary.

Modifying PATH on Windows 10:

In the Start Menu or taskbar search, search for "environment variable".
Select "Edit the system environment variables".
Click the "Environment Variables" button at the bottom.
Double-click the "Path" entry under "System variables".
With the "New" button in the PATH editor, add C:\Program Files\Git\bin\ and C:\Program Files\Git\cmd\ to the end of the list.
Close and re-open your console.

And added **C:\Users\user\AppData\Roaming\npm** from user variables to system variables.
Hope it will work!

**Comment by SakuraPuare** [comment] 2021-05-21 05:28
> When I use npm install,it says
> ![image](https://user-images.githubusercontent.com/51043917/93785135-5157f400-fc60-11ea-8c31-e782adf86c49.png)
> 
> Linux Debian
> Arm64

Don't use root

**Comment by Revadike** [comment] 2021-05-31 14:51
Dupe of https://github.com/Revadike/epicgames-freebies-claimer/issues/44

**Closed by Revadike** 2021-05-31 14:51 UTC
