### ISSUE TITLE
(Error: We could not confirm your purchase at this time.  Please try again later.)

### ISSUE THREAD

**Issue by PattyXD** [Revadike/epicgames-freebies-claimer#195] opened 2022-03-18 07:27 UTC
### Expected Behavior
I expect it to claim some games

### Actual Behavior
it dont claim and give me error: (Error: We could not confirm your purchase at this time.  Please try again later.)

### Steps to Reproduce the Problem

  1. Using Github actions

### Specifications

  - `epicgames-freebies-claimer` Version: 1.5.8
  - Platform / OS: idk
  - Node Version: idk

**Comment by Revadike** [comment] 2022-03-18 11:21
Dupe of https://github.com/Revadike/epicgames-freebies-claimer/issues/172

**Closed by Revadike** 2022-03-18 11:21 UTC
Labels: bug
