### ISSUE TITLE
ERROR | TypeError: Cannot read properties of undefined (reading 'id')

### ISSUE THREAD

**Issue by XEGARE** [Revadike/epicgames-freebies-claimer#159] opened 2021-12-09 16:44 UTC
Hello. On the latest version I get:
`2021-12-09 | 21:40:05.268 | INFO  | Epicgames Freebies Claimer (1.5.6) by Revadike`
`2021-12-09 | 21:40:10.124 | ERROR | TypeError: Cannot read properties of undefined (reading 'id')`
    `at getOfferId (F:\EpicClaimer\src\gamePromotions.js:37:30)`
    `at processTicksAndRejections (node:internal/process/task_queues:96:5)`
    `at async F:\EpicClaimer\src\gamePromotions.js:52:18`
    `at async Promise.all (index 0)`
    `at async freeGamesPromotions (F:\EpicClaimer\src\gamePromotions.js:50:22)`
    `at async F:\EpicClaimer\claimer.js:91:30`

**Comment by Stinosko** [comment] 2021-12-09 16:59
Same issue here

**Comment by ArmoredVortex** [comment] 2021-12-09 17:05
Facing the same Issue

**Comment by Revadike** [comment] 2021-12-09 17:11
Yes, I also saw this. The response structure of the free promotions API endpoint must have changed.

**Comment by Revadike** [comment] 2021-12-09 17:32
The exact problem is that getting product info from slug `godfall--challenger-edition` is returning an error.

**Comment by ArmoredVortex** [comment] 2021-12-09 17:59
I just tried to claim the game manually and it gave me a captcha to solve.
Maybe that's the cause for this ?

**Comment by Revadike** [comment] 2021-12-09 18:08
No, it's not. I actually will be pushing a fix in a minute.

**Comment by Revadike** [comment] 2021-12-09 18:17
Should be fixed in V1.5.7

**Closed by Revadike** 2021-12-09 18:17 UTC
Labels: bug

**Comment by ffuubarbuzz** [comment] 2021-12-09 19:55
@jackblk could you please release new container?

**Comment by jackblk** [comment] 2021-12-10 00:19
@ffuubarbuzz it was released 5 hours ago. It's having a big with the notification, I will fix it later.

**Comment by jackblk** [comment] 2021-12-10 03:36
@ffuubarbuzz ah by the way, if you haven't notice, the `latest` tag now supports apprise. You can check out [the wiki, i've updated it](https://github.com/Revadike/epicgames-freebies-claimer/wiki/User-Guide-(Docker)#notification-with-apprise).

[Github action guide is also updated.](https://github.com/Revadike/epicgames-freebies-claimer/wiki/Automatically-collect-freebies-with-Github-Actions#notification-with-apprise)

**Comment by zzz6839** [comment] 2022-04-21 05:24
@Revadike sir, same issue happened on v1.5.8.

22-04-21 | 13:17:52.675 | INFO | Epicgames Freebies Claimer (1.5.8) by Revadike[39m
m 2022-04-21 | 13:17:57.520 | ERROR | TypeError: Cannot read properties of undefined (reading 'id')[39m[22m

m at getOfferId (/app/src/gamePromotions.js:42:25)[39m[22m
m at processTicksAndRejections (node:internal/process/task_queues:96:5)[39m[22m
m at async /app/src/gamePromotions.js:59:33[39m[22m
m at async Promise.all (index 0)[39m[22m
m at async freeGamesPromotions (/app/src/gamePromotions.js:57:22)[39m[22m
m at async /app/claimer.js:91:30[39m[22m
